export const SERVICE_AREAS = [
  'New York, NY',
  'Los Angeles, CA',
  'Chicago, IL',
  'Houston, TX',
  'Phoenix, AZ',
  'Philadelphia, PA',
  'San Antonio, TX',
  'San Diego, CA',
  'Dallas, TX',
  'San Jose, CA',
  'Austin, TX',
  'Jacksonville, FL',
  'Fort Worth, TX',
  'Columbus, OH',
  'Charlotte, NC',
  'San Francisco, CA',
  'Indianapolis, IN',
  'Seattle, WA',
  'Denver, CO',
  'Washington, DC',
  'Boston, MA',
  'El Paso, TX',
  'Nashville, TN',
  'Detroit, MI',
  'Oklahoma City, OK',
  'Portland, OR',
  'Las Vegas, NV',
  'Memphis, TN',
  'Louisville, KY',
  'Baltimore, MD',
  'Milwaukee, WI',
  'Albuquerque, NM',
  'Tucson, AZ',
  'Fresno, CA',
  'Mesa, AZ',
  'Sacramento, CA',
  'Atlanta, GA',
  'Kansas City, MO',
  'Colorado Springs, CO',
  'Miami, FL',
  'Raleigh, NC',
  'Omaha, NE',
  'Long Beach, CA',
  'Virginia Beach, VA',
  'Oakland, CA',
  'Minneapolis, MN',
  'Tulsa, OK',
  'Arlington, TX',
  'Tampa, FL',
  'New Orleans, LA'
]

export const MASSAGE_SPECIALTIES = [
  'Swedish Massage',
  'Deep Tissue',
  'Sports Massage',
  'Therapeutic Massage',
  'Relaxation Massage',
  'Hot Stone Massage',
  'Prenatal Massage',
  'Trigger Point Therapy',
  'Myofascial Release',
  'Reflexology',
  'Shiatsu',
  'Thai Massage',
  'Aromatherapy Massage',
  'Lymphatic Drainage',
  'Injury Recovery'
]

export const COMMISSION_TIERS = {
  BRONZE: { level: 1, name: 'Bronze', rate: 60, minBookings: 0 },
  SILVER: { level: 2, name: 'Silver', rate: 70, minBookings: 5 },
  GOLD: { level: 3, name: 'Gold', rate: 80, minBookings: 15 }
}

export const SQUARE_APPOINTMENTS_URL = process.env.SQUARE_APPOINTMENTS_URL || 'https://squareup.com/appointments'
